# Generated by Django 5.1.3 on 2025-01-11 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_order_customer_alter_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
