# Generated by Django 5.1.3 on 2025-01-13 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_name_item_itemname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='itemname',
            new_name='name',
        ),
    ]
