# Generated by Django 5.1.3 on 2025-01-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_itemname_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivery', 'Delivery'), ('Customer Pick-up', 'Customer Pick-up')], default='Pending', max_length=50),
        ),
    ]
